### ISSUE TITLE
[Reputation Oracle] Refactor error handling

### ISSUE THREAD

**Issue by Dzeranov** [humanprotocol/human-protocol#2928]
**Description**
Current error handling mechanism needs to be reworked:
1. Errors need to be standardised, with the ability to create custom error classes and rely on `instanceof` operator.
2. Error context should be in the error object itself (e.g. userId etc.).
3. Error messages should not contain any dynamic values.
4. Handle database errors on repository level, do not throw httpexceptions on service level.

**Motivation**
1. Cleaner and easier to maintain codebase.
2. Improve observability and troubleshooting.

**Roadmap**
Refactor error handling in the following modules:
- [x] [Auth](https://github.com/humanprotocol/human-protocol/pull/2960)
- [x] [Cron-job](https://github.com/humanprotocol/human-protocol/pull/3062)
- [x] [Escrow-completion](https://github.com/humanprotocol/human-protocol/pull/3057)
- [x] ~~Health~~
- [x] [KYC](https://github.com/humanprotocol/human-protocol/pull/2937)
- [x] [Payout](https://github.com/humanprotocol/human-protocol/pull/3062) 
- [x] [Qualification](https://github.com/humanprotocol/human-protocol/pull/2944)
- [x] [Reputation](https://github.com/humanprotocol/human-protocol/pull/2947)
- [x] [Sendgrid](https://github.com/humanprotocol/human-protocol/pull/3062)
- [x] [Storage](https://github.com/humanprotocol/human-protocol/pull/3062)
- [x] [User](https://github.com/humanprotocol/human-protocol/pull/3042)
- [x] [Web3](https://github.com/humanprotocol/human-protocol/pull/3062)
- [x] [Webhook](https://github.com/humanprotocol/human-protocol/pull/2968)
